---
abstract: 'Backwards-compatible handling of new syntactic features'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: any-feature
provides:
  any::feature:
    file: lib/any/feature.pm
    version: 1.100840
requires:
  Capture::Tiny: 0
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Perl::Version: 0
  Scalar::Util: 0
  Test::More: 0.88
  UNIVERSAL::require: 0
  mysubs: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=any-feature
  homepage: http://search.cpan.org/dist/any-feature/
  repository: http://github.com/hanekomu/any-feature
version: 1.100840
