---
abstract: 'Backwards-compatible handling of new syntactic features'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  IO::Capture::Stderr: 0
  IO::Capture::Stdout: 0
  Test::More: 0.70
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: any-feature
no_index:
  directory:
    - inc
    - t
requires:
  Perl6::Say: 0
  Perl::Version: 0
  Sub::Delete: 0
  UNIVERSAL::require: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
